# Generated by Django 5.2.1 on 2025-06-25 08:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
        ('tweets', '0004_alter_tweet_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookmarksModel',
            new_name='Bookmark',
        ),
    ]
