# Generated by Django 5.2.1 on 2025-06-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_rename_bookmarksmodel_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='tweets',
            new_name='tweet',
        ),
    ]
