# Generated by Django 5.2.1 on 2025-06-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_name',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
