# Generated by Django 5.2.1 on 2025-06-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_name',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
