version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - db_data:/app/db_data
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --log-level debug --reload
    ports:
      - "8000:8000"
    tty: true
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
