# Generated by Django 5.2.1 on 2025-06-15 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_rename_comment_comment_conent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='conent',
            new_name='content',
        ),
    ]
