# Generated by Django 5.2.1 on 2025-06-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retweet',
            old_name='retweets',
            new_name='retweet',
        ),
    ]
