# Generated by Django 5.2.1 on 2025-05-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=22, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone_number', models.CharField(max_length=13)),
                ('account_name', models.CharField(null=True)),
                ('self_introduction', models.TextField(null=True)),
                ('address', models.CharField(null=True)),
                ('web_site', models.TextField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('background_image', models.ImageField(null=True, upload_to='')),
                ('avater', models.ImageField(null=True, upload_to='')),
                ('follow', models.IntegerField(null=True)),
                ('info_flg', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
