# Generated by Django 5.2.1 on 2025-06-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'フォロー'), ('like', 'いいね'), ('retweet', 'リツイート'), ('comment', 'コメント')], default=None, max_length=10),
        ),
    ]
