# Generated by Django 5.2.1 on 2025-06-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LK', 'like'), ('FL', 'follow'), ('CM', 'comment'), ('RT', 'retweet')], default=None, max_length=2),
        ),
    ]
